testbucket8.1

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -3,13 +3,13 @@ name: Deploy and Manage Static Website to S3
 on:
   push:
     branches:
-      - master          # Trigger deploy on push to the master branch
+      - master
     tags:
-      - 'delete-*'      # Trigger destroy on push to tags matching 'delete-*'
+      - 'delete-*'
 
 jobs:
   deploy:
-    if: ${{ github.ref == 'refs/heads/master' }}  # Run deploy only if the push is to the master branch
+    if: ${{ github.ref == 'refs/heads/master' }}
     runs-on: ubuntu-latest
 
     steps:
@@ -44,7 +44,7 @@ jobs:
           echo "Your website is available at $website_url"
 
   destroy:
-    if: ${{ startsWith(github.ref, 'refs/tags/delete-') }}  # Run destroy only if the push is to a tag matching 'delete-*'
+    if: ${{ startsWith(github.ref, 'refs/tags/delete-') }}
     runs-on: ubuntu-latest
 
     steps:
@@ -67,15 +67,15 @@ jobs:
         working-directory: ./terraform
         run: terraform init
 
+      - name: Show Terraform State
+        working-directory: ./terraform
+        run: terraform state list
+
+      - name: Show Terraform Outputs
+        working-directory: ./terraform
+        run: terraform output
+
       - name: Destroy Terraform
         working-directory: ./terraform
-        run: terraform destroy -auto-approve
-
-
-        - name: Show Terraform State
-  working-directory: ./terraform
-  run: terraform state list
-
-- name: Show Terraform Outputs
-  working-directory: ./terraform
-  run: terraform output
+        run: |
+          terraform destroy -auto-approve || { echo "Terraform destroy failed"; exit 1; }
